"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
from urllib.parse import quote

import dj_database_url
from decouple import Csv, config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-2jiirpq8&df%@p*hdczpkbcr07by17k$c9lkzco9olphh+p!e5')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

if not DEBUG and SECRET_KEY.startswith('django-insecure'):
    # Evita desplegar por accidente con la clave de desarrollo: si DEBUG=False (producción)
    # hace falta una SECRET_KEY real puesta a mano en las variables de entorno.
    raise ImproperlyConfigured(
        "Configura una SECRET_KEY real en producción (variable de entorno SECRET_KEY)."
    )

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=Csv())

# Django pone "same-origin" por defecto, lo que corta window.opener en el popup de login con
# Google (el script de Google necesita avisarle a esta pestaña que el login terminó vía
# window.opener.postMessage). "same-origin-allow-popups" sigue protegiendo contra ataques de
# terceros pero permite que los popups que SÍ abrimos nosotros mantengan esa referencia.
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# Render (y la mayoría de PaaS) terminan TLS en un proxy y reenvían HTTP internamente.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'usuarios',
    'citas',
    'pagos',
    'frontend',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

_DEFAULT_DB_URL = 'postgres://{user}:{password}@{host}:{port}/{name}'.format(
    # user/password van con quote(): si tienen caracteres reservados de URL (?, @, /, #, %),
    # sin esto arman una URL inválida y dj_database_url la interpreta mal (o directamente falla).
    user=quote(config('DB_USER', default='barberia_user'), safe=''),
    password=quote(config('DB_PASSWORD', default=''), safe=''),
    host=config('DB_HOST', default='localhost'),
    port=config('DB_PORT', default='5432'),
    name=config('DB_NAME', default='barberia_db'),
)

DATABASES = {
    # DATABASE_URL la inyecta el proveedor (ej. Supabase) en producción.
    # En local, se arma desde las variables DB_* del .env.
    # Supabase (y la mayoría de proveedores externos) exponen Postgres por internet, así que
    # ahí SÍ hace falta forzar SSL con DB_SSL_REQUIRE=True (en local, contra un Postgres propio,
    # se deja en False).
    'default': dj_database_url.config(
        default=_DEFAULT_DB_URL,
        conn_max_age=600,
        ssl_require=config('DB_SSL_REQUIRE', default=False, cast=bool),
    )
}

AUTH_USER_MODEL = 'usuarios.Usuario'


# Email

EMAIL_BACKEND = config("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Correo del dueño de la barbería al que llegan los avisos de nuevas citas y el resumen diario.
OWNER_NOTIFICATION_EMAIL = config("OWNER_NOTIFICATION_EMAIL", default=EMAIL_HOST_USER)

# Login con Google (Google Identity Services) — ver usuarios/views.py::GoogleLoginView.
# Solo hace falta el Client ID (público, va también en el frontend); no requiere client secret
# porque solo verificamos el ID token que ya firmó Google, no hacemos el intercambio OAuth completo.
GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID", default="")


# Mientras el negocio todavía no está aceptando pagos reales, las citas se confirman al
# instante (sin pasar por PayPal) y se avisa por email — toda la integración de PayPal de abajo
# queda lista y probada, pero no se usa hasta poner esta bandera en True.
PAGOS_REALES_HABILITADOS = config("PAGOS_REALES_HABILITADOS", default=False, cast=bool)

# PayPal (Orders API v2) — ver pagos/paypal.py
PAYPAL_MODE = config("PAYPAL_MODE", default="sandbox")  # "sandbox" o "live"
PAYPAL_CLIENT_ID = config("PAYPAL_CLIENT_ID", default="")
PAYPAL_CLIENT_SECRET = config("PAYPAL_CLIENT_SECRET", default="")
PAYPAL_WEBHOOK_ID = config("PAYPAL_WEBHOOK_ID", default="")
PAYPAL_API_BASE = (
    "https://api-m.paypal.com" if PAYPAL_MODE == "live" else "https://api-m.sandbox.paypal.com"
)

# URL pública del propio backend, usada para armar los return_url/cancel_url que se le pasan a
# PayPal al crear una orden (en local suele ser http://127.0.0.1:8000).
SITE_URL = config("SITE_URL", default="http://127.0.0.1:8000")


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Límite de intentos en endpoints sensibles (login/registro) para frenar fuerza bruta;
    # ver el atributo throttle_scope="auth" en usuarios/views.py.
    'DEFAULT_THROTTLE_RATES': {
        'auth': '10/min',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Barbería API',
    'DESCRIPTION': 'API de reservas y pagos para una barbería.',
    'VERSION': '1.0.0',
}


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Endurecimiento para producción (no aplica en local, donde DEBUG=True y se corre sobre HTTP).
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Arranca en 1 semana; una vez confirmado que todo funciona bien por HTTPS, se puede subir
    # (ej. a 1 año) para que los navegadores fuercen HTTPS de entrada en visitas futuras.
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
