# Generated by Django 5.0.14 on 2026-09-25 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_seed_servicios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_total_minutos', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tarifa_reserva', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo_pago', models.CharField(choices=[('deposito', 'Depósito'), ('completo', 'Pago completo')], default='deposito', max_length=10)),
                ('monto_a_pagar_online', models.DecimalField(decimal_places=2, max_digits=6)),
                ('saldo_pagado_en_persona', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_show', 'No se presentó'), ('expirada', 'Expirada')], default='pendiente_pago', max_length=20)),
                ('deposito_perdido', models.BooleanField(default=False)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('paypal_order_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL)),
                ('extras', models.ManyToManyField(blank=True, related_name='citas', to='citas.extra')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='citas.servicio')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
                'indexes': [models.Index(fields=['fecha', 'hora_inicio'], name='citas_cita_fecha_49634a_idx')],
            },
        ),
    ]
